version: "3"

services:

  minio:
    image: minio/minio
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler &&
        minio server /data
    env_file:
      - config-minio
    ports:
      - "9000:9000"
    volumes:
      - ./.data/minio:/data
    restart: always
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
